# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a42a4afbf0c622a09c59850f3bdfd5b4782bd19715719d6fd6a279bcf52ba39b7b25fdaa22b8083e35dc01652760138cd731673d59212878c9ce48e05aef1ef

test:
  secret_key_base: 58db7b45ff1966b124f130bf1a12f0f329234ce35fe0fd4834d15c70074ad9b35649cf75c357a8d51f80da2bdce0aaeb8ca05ddd846c7b2a1f4bcebaff54deb2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
